// Exercise 18.5: Modify the following main function to catch any of the
// exception types shown in Figure 18.1 (p. 783):

// int main() {
//   // use of the C++ standard library
// }

// The handlers should print the error message associated with the exception
// before calling abort (defined in the header cstdlib) to terminate main.
